# GenerateEmbeddedAssets.cmake
#
# Called at configure time (execute_process) and at build time (add_custom_command).
#
# Usage:
#   cmake -DSOURCE_DIR=<repo-root> -DOUTPUT_DIR=<generated-dir>
#         -P cmake/GenerateEmbeddedAssets.cmake
#
# Outputs:
#   ${OUTPUT_DIR}/EmbeddedAssets.h
#   ${OUTPUT_DIR}/EmbeddedAssets.cpp

cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED SOURCE_DIR OR NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "GenerateEmbeddedAssets.cmake requires -DSOURCE_DIR=... -DOUTPUT_DIR=...")
endif()

file(MAKE_DIRECTORY "${OUTPUT_DIR}")

# ── Write header ───────────────────────────────────────────────────────────────
file(WRITE "${OUTPUT_DIR}/EmbeddedAssets.h"
        "#pragma once
#include <cstddef>

// Auto-generated by cmake/GenerateEmbeddedAssets.cmake -- do not edit by hand.

struct EmbeddedAsset {
    const char*          category; // \"pus\" | \"scissors\" | \"urbino\" | \"font\"
    const char*          name;     // filename stem (without extension)
    const unsigned char* data;
    std::size_t          size;
};

extern const EmbeddedAsset kEmbeddedAssets[];
extern const std::size_t   kEmbeddedAssetCount;
")

# ── Start source file ──────────────────────────────────────────────────────────
file(WRITE "${OUTPUT_DIR}/EmbeddedAssets.cpp"
        "// Auto-generated by cmake/GenerateEmbeddedAssets.cmake -- do not edit by hand.
#include \"EmbeddedAssets.h\"

")

# ── Emit one byte-array per asset ─────────────────────────────────────────────

# Image and font categories
set(CATEGORIES pus scissors urbino font)

set(ASSET_COUNT 0)
set(REGISTRY_ENTRIES "")

foreach(CAT ${CATEGORIES})

    set(CAT_PATTERNS)

    # Images
    if(NOT CAT STREQUAL "font")
        foreach(EXT png jpg jpeg bmp tga PNG JPG JPEG BMP TGA)
            list(APPEND CAT_PATTERNS
                    "${SOURCE_DIR}/assets/${CAT}/*.${EXT}"
            )
        endforeach()

        # Fonts
    else()
        foreach(EXT ttf otf TTF OTF)
            list(APPEND CAT_PATTERNS
                    "${SOURCE_DIR}/assets/font/*.${EXT}"
            )
        endforeach()
    endif()

    file(GLOB CAT_FILES ${CAT_PATTERNS})

    if(NOT CAT_FILES)
        continue()
    endif()

    list(SORT CAT_FILES)

    foreach(ASSET_FILE ${CAT_FILES})

        get_filename_component(STEM "${ASSET_FILE}" NAME_WE)

        # Build a valid C identifier
        set(RAW_ID "${CAT}_${STEM}")
        string(REGEX REPLACE "[^A-Za-z0-9_]" "_" VAR_ID "${RAW_ID}")

        # Read file as hex bytes
        file(READ "${ASSET_FILE}" HEX_DATA HEX)

        string(REGEX REPLACE
                "([0-9a-fA-F][0-9a-fA-F])"
                "0x\\1,"
                HEX_BYTES
                "${HEX_DATA}"
        )

        file(APPEND "${OUTPUT_DIR}/EmbeddedAssets.cpp"
                "// ${CAT}/${STEM}\n"
                "static const unsigned char kData_${VAR_ID}[] = {\n"
                "    ${HEX_BYTES}\n"
                "};\n"
                "\n"
        )

        string(APPEND REGISTRY_ENTRIES
                "    { \"${CAT}\", \"${STEM}\", kData_${VAR_ID}, sizeof(kData_${VAR_ID}) },\n"
        )

        math(EXPR ASSET_COUNT "${ASSET_COUNT} + 1")

    endforeach()

endforeach()

# ── Emit registry table ────────────────────────────────────────────────────────
file(APPEND "${OUTPUT_DIR}/EmbeddedAssets.cpp"
        "const EmbeddedAsset kEmbeddedAssets[] = {\n"
        "${REGISTRY_ENTRIES}"
        "};\n"
        "\n"
        "const std::size_t kEmbeddedAssetCount = ${ASSET_COUNT};\n"
)

message(STATUS
        "GenerateEmbeddedAssets: wrote ${ASSET_COUNT} assets to ${OUTPUT_DIR}"
)